### PR TITLE
Change the inline xml code to strings

### PR DESCRIPTION
**Pull request by Takika**
Change the inline xml code to strings for better readability and syntax hilite.

### CODE REVIEW

**Comment by fmbiete** [comment]
The problem about this is that to get a nice format (as you used), we must do string concatenations. Those concat have an execution cost.

With the inline xml code we have a formatted string, but we lose the syntax highlight.

For me, 2 is better than 1 (I use kate as editor), but if you find another solution it would be great

**Comment by Takika** [comment]
We can use one (multi-line) sprintf per EOXML instead of concatenations.

**Comment by fmbiete** [comment]
Yes, that would be perfect. Can you change this pull request please?

**Comment by Takika** [comment]
Just changed the concatenations to multiline sprintf, but I think this is really ugly now :(

**Comment by fmbiete** [comment]
Yes, it's a bit ugly. :laughing: 
But the worse thing is that we are defining multiple string object and doing a sprintf to concatenate them.

How about something like this?? Would be OK with your editor?
```
sprintf("<?xml version='1.0' encoding='utf-8' ?>
<C:calendar-multiget xmlns='DAV:' xmlns:C='urn:ietf:params:xml:ns:caldav'>
<prop><getetag/><C:calendar-data/></prop>
%s
</C:calendar-multiget>", $hrefs);
```

**Pull request closed without merging**
